# Zerver Configuration Template

# This is a sample configuration file for Zerver applications.
# Copy this file and customize it for your deployment environment.

# Server Configuration
[server]
# Host to bind the server to
host = "127.0.0.1"

# Port to listen on
port = 8080

# Debug mode (enables additional logging)
debug = false

# Request timeout in milliseconds
request_timeout_ms = 30000

# Maximum request body size in bytes
max_request_size = 1048576  # 1MB

# Maximum number of concurrent connections
max_connections = 1000

# Database Configuration (if using database effects)
[database]
# Database URL (format depends on your database driver)
url = "postgresql://user:password@localhost:5432/zerver_db"

# Connection pool size
pool_size = 10

# Connection timeout in milliseconds
connection_timeout_ms = 5000

# Query timeout in milliseconds
query_timeout_ms = 10000

# Observability Configuration
[observability]
# Enable request tracing
tracing_enabled = true

# Trace export format ("json" or "none")
trace_format = "json"

# Enable metrics collection
metrics_enabled = false

# Metrics export endpoint (if metrics_enabled = true)
metrics_endpoint = "http://localhost:9091/metrics"

# OTLP exporter configuration (for advanced observability)
[otlp]
# OTLP endpoint URL
endpoint = "http://localhost:4318/v1/traces"

# OTLP headers (key=value pairs)
headers = "service.name=zerver-app,service.version=1.0.0"

# Batch size for trace exports
batch_size = 512

# Export interval in milliseconds
export_interval_ms = 5000

# Security Configuration
[security]
# CORS allowed origins (comma-separated)
cors_origins = "*"

# CORS allowed methods
cors_methods = "GET,POST,PUT,PATCH,DELETE,OPTIONS"

# CORS allowed headers
cors_headers = "Content-Type,Authorization,X-Requested-With"

# Rate limiting
[rate_limiting]
# Enable rate limiting
enabled = false

# Requests per minute per IP
requests_per_minute = 60

# Burst limit
burst_limit = 10

# Logging Configuration
[logging]
# Log level (debug, info, warn, error)
level = "info"

# Log format (json, text)
format = "text"

# Enable structured logging
structured = true

# Log file path (leave empty for stdout)
file_path = ""

# Development Configuration
[development]
# Enable hot reload (if supported)
hot_reload = false

# Enable detailed error pages
detailed_errors = true

# Enable request/response logging
request_logging = true

# Environment-specific overrides
[production]
# Override settings for production
debug = false
detailed_errors = false
request_logging = false
metrics_enabled = true

[staging]
# Override settings for staging
debug = false
detailed_errors = true
request_logging = true
metrics_enabled = true

# Custom Application Settings
[app]
# Application-specific configuration
app_name = "My Zerver App"
version = "1.0.0"
environment = "development"

# Feature flags
enable_feature_x = true
enable_feature_y = false

# Custom settings
custom_setting_1 = "value1"
custom_setting_2 = 42