name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    steps:
        - uses: actions/checkout@v4
    
        - name: Cache Zig build cache
          id: cache-zig
          uses: actions/cache@v4
          with:
            path: ~/.zig-cache
            key: ${{ runner.os }}-zig-${{ hashFiles('build.zig') }}
            restore-keys: |
              ${{ runner.os }}-zig-
    
        - name: Install Zig
          uses: ziglang/setup-zig@v1
          with:
            zig-version: 0.15.2
    
    - name: Build
      run: zig build

    - name: Test
      run: zig test
    
    - name: Check formatting
      run: zig fmt --check src/ examples/
